### ISSUE TITLE
frontend: Create "Help" page

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/POC-Trustless-Work#21] opened 2024-11-21 03:10 UTC
## **Description**:

Add a "Help" page accessible from a section in the header. This page should be structured using the `Accordion` component from ShadCN UI (reference: [Accordion Component Documentation](https://ui.shadcn.com/docs/components/accordion)). The content for this page can be filled with placeholder text (e.g., Lorem Ipsum) for now.

## **Requirements**:

1. Add a "Help" link or button in the header section that navigates to the new "Help" page.
2. On the "Help" page, implement the `Accordion` component from ShadCN UI to organize information in collapsible sections.
3. Use placeholder text (Lorem Ipsum) within each section of the accordion for demonstration purposes.

## Validations:

1. The "Help" link in the header should navigate correctly to the "Help" page.
2. The accordion on the "Help" page should be implemented as per the ShadCN UI design specifications, allowing sections to expand and collapse as intended.
3. Placeholder text should display correctly within each accordion section.
4. It should works on light / dark mode.
5. Must be fully responsive.

## Tests:

1. Test navigation from the header to the "Help" page.
2. Verify that the accordion component functions correctly, expanding and collapsing each section smoothly.
3. Ensure the placeholder text displays in each section of the accordion without styling or alignment issues.

## Recommendation:

Stick closely to the ShadCN UI guidelines for component usage, especially regarding styling and layout within the accordion. This will ensure visual consistency across the application.

**Comment by Michaelkingsdev** [comment] 2024-11-21 04:32
Hello, @JoelVR17 
My name is Michael. I am an experienced nextjs developer. I have 4 years of experience as a fullstack developer. 
I will create a fully responsive "Help" page with navigation from the header using next/link. The page will use the ShadCN UI Accordion component to organize placeholder content into collapsible sections, ensuring smooth functionality and alignment with the design specs. I’ll ensure compatibility with both light and dark modes, test navigation, and validate the accordion’s responsiveness and usability on all devices. Can this task be assigned to me? My ETA is 48hrs from the start of ODHack.

**Comment by Benjtalkshow** [comment] 2024-11-21 14:10
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

Let me work on this issue and deliver in the next 24 hrs

**Comment by Ugo-X** [comment] 2024-11-21 14:56
I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 92 significant contributions across 19 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  


I am confident I can implement this design according to Ui specifications, would love to work on it.

**Comment by Bran18** [comment] 2024-11-21 15:35
Hello there. I’m Brandon, part of the ⛩️ Dojo Coding community, and I would love to contribute to this project! 🚀  This might be my first contribution here.

I've done quite a few accordion-related components and pages in our apps, feel free to check out the one from MB (https://masterbots.ai/) as one example xD. This full section is pretty much accordions being toggle and showing content (not that easy but yeah xD) I would love to help out with creating the one you need and adding all the elements it needs. I will be following the strategy we use in our products. 

Lmk if I can start working on it.  Here’s my GitHub profile: GitHub: https://github.com/Bran18 and my OnlyDust profile: https://app.onlydust.com/u/Bran18. 

BTW tks for taking the time 🙏

**Comment by Jethrolopwus** [comment] 2024-11-21 15:52
I'd be happy to do this.

**Comment by KevinLatino** [comment] 2024-11-21 16:01
Hello @JoelVR17 My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding ⛩️, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

I will add a "Help" page to the application, accessible from the header section. The page will feature the Accordion component from ShadCN UI, which will be used to organize information into collapsible sections. For now, I will populate the sections with placeholder text (Lorem Ipsum). The "Help" link in the header will navigate correctly to this new page. I will ensure that the accordion works as intended, allowing sections to expand and collapse, and verify it works seamlessly in both light and dark modes. Additionally, the page will be fully responsive. Finally, I will test the navigation and accordion functionality to ensure everything works smoothly.

Here is an example of a Frontend Project that I have made:
https://buildmyevent.xyz/

**Comment by MullerTheScientist** [comment] 2024-11-21 16:27
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. please can i address this issue

**Comment by melnikga** [comment] 2024-11-21 16:36
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga
ETA: 2 days

**Comment by chibokaxavier** [comment] 2024-11-21 17:22
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. I would really love to be assigned this issue and work on this project.

**Comment by Amarjeet325** [comment] 2024-11-21 18:19
Could  I try this one?

**Comment by JoelVR17** [comment] 2024-11-21 19:21
This issue is for you @Michaelkingsdev! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application.

**Comment by Michaelkingsdev** [comment] 2024-11-21 23:44
> This issue is for you @Michaelkingsdev! 🚀 Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.
> 
> Many thanks to all the other dev's who sent in their application.

Thanks a lot.

**Closed** 2024-11-23 03:18 UTC
Labels: enhancement, good first issue, ODHACK10, external-contributors, Maintainer - Joel Vargas
